# Generated by Django 5.1.3 on 2024-11-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clan_clanmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
